version: '3'
services:
  mysql:
     container_name: mysql
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        - /mysql/data:/var/lib/mysql 
     ports:
        - "6000:3306"
