apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-rc-pod
  ports:
    - name: client
      port: 3306
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-rc-pod
    spec:
      containers:
      - name: mysql
        image: prateekjainaa/mysql:1
        ports:
        - containerPort: 3306
